language: php

php:
  - 5.6
  - 7
  - 7.1

sudo: required

services:
  - mysql

before_script:
  - set -e
  - wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-2-amd64.deb
  - sudo dpkg -i couchbase-release-1.0-2-amd64.deb
  - sudo apt-get update
  - sudo apt-get install libcouchbase-dev
  - wget http://packages.couchbase.com/releases/4.6.0-DP/couchbase-server-enterprise_4.6.0-DP-ubuntu12.04_amd64.deb
  - sudo dpkg -i couchbase-server-enterprise_4.6.0-DP-ubuntu12.04_amd64.deb
  - cd /opt/couchbase
  - ./bin/couchbase-server -- -noinput -detached
  - sleep 5
  - ./bin/couchbase-cli cluster-init -c 127.0.0.1:8091  --cluster-username=Administrator --cluster-password=password --cluster-port=8091 --cluster-index-ramsize=512 --cluster-ramsize=512 --services=data,query,index
  - ./bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=testing --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=512  --bucket-replica=1 -u Administrator -p password
  - ./bin/cbq -c 127.0.0.1:8091 --script "CREATE PRIMARY INDEX ON testing USING GSI;"
  - mysql -e 'create database testing;'
  - pecl install couchbase
  - cd $TRAVIS_BUILD_DIR
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit