language: php

php:
  - 5.6
  - 7
  - 7.1

sudo: required

services:
  - mysql

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - wget http://packages.couchbase.com/releases/4.1.0/couchbase-server-community_4.1.0-ubuntu12.04_amd64.deb
  - sudo dpkg -i couchbase-server-community_4.1.0-ubuntu12.04_amd64.deb
  - cd /opt/couchbase
  - ./bin/couchbase-server -- -noinput -detached
  - sleep 20
  - ./bin/couchbase-cli cluster-init -c 127.0.0.1:8091  --cluster-init-username=Administrator --cluster-init-password=password --cluster-init-port=8091 --cluster-init-ramsize=1024
  - ./bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=test --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=512  --bucket-replica=1 -u Administrator -p password
  - pecl install couchbase
  - mysql -e 'create database testing;'

script:
  - vendor/bin/phpunit